services:
  chromadb:
    image: chromadb/chroma:1.3.8.dev12
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8010:8000"
    volumes:
      - ./chroma-db:/data
    
  redis:
    image: redis:8.4-bookworm
    ports:
      - "6379:6379"
